# Generated by Django 2.1.1 on 2018-09-25 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_song_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='pwd_hash',
            field=models.CharField(editable=False, max_length=256),
        ),
    ]
