# Generated by Django 2.1.1 on 2018-10-05 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180925_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.CharField(default='n/a', max_length=256),
        ),
    ]
