# Generated by Django 2.1.1 on 2018-10-05 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_song_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
        migrations.AlterField(
            model_name='play',
            name='score',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
