# Generated by Django 2.1.1 on 2018-10-05 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20181005_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
